<?php
    $cartBillingAddress = $this->getBillingAddress();
    $countries = $this->getCountryName();
    //$cartBillingAddress = $this->getCart()->getBillingAddress();
   /*";
    print_r($countries);
     die; */
     
       
?>
<form action="<?php echo $this->getUrl('*/adminhtml_order/saveBillingAddress/');?>" Method="POST" id="cartForm">
    <?php echo $this->getBlockHtml('formkey');?>

    <table class="table">
                                  <tr>
                                      <td>
                                          <input type="text" name="billing[address]" id="address" value="<?php if($cartBillingAddress->street){echo $cartBillingAddress->street;}if($cartBillingAddress->address){echo $cartBillingAddress->address;}?>"
                                              placeholder="Address" class="form-control" required>
                                      </td>
                                    </tr>  
                                    <tr>  
                                        <td>
                                          <input type=" text" name="billing[city]" id="lastname" value="<?php echo $cartBillingAddress->city?>"
                                              placeholder="City" class="form-control" required>
                                        </td> 
                                  </tr>
                                  <tr>
                                      <td>
                                          <input type="text" name="billing[state]" id="state" value="<?php if($cartBillingAddress->region){echo $cartBillingAddress->region;}if($cartBillingAddress->state){echo $cartBillingAddress->state;}?>"
                                              placeholder="State" class="form-control" required>
                                      </td>
                                  </tr>
                                  <tr>  
                                      <td>
                                          <input type="text" name="billing[zipcode]" id="zipcode" value="<?php if($cartBillingAddress->zipcode){echo $cartBillingAddress->zipcode;}if($cartBillingAddress->postcode){echo $cartBillingAddress->postcode;}?>"
                                              placeholder="Zipcode" class="form-control" required>
                                      </td>
                                  </tr>
                                  <tr>
                                      <td>
                                      
                                       <select id="country_name" name="billing[country]" required>
                                            <option value="">Select Country</option>
                                            <?php foreach($countries as $key => $country):?>
                                                <option name="country_name" value="<?php echo $country['country_id'];?>"
                                                 <?php if ($cartBillingAddress['country_id'] == $country['country_id']){ echo "Selected";}?><?php if ($cartBillingAddress['country'] == $country['country_id']){ echo "Selected";}?>>
                                                 <?php echo $country['name']?>
                                                 </option>
                                            <?php endforeach;?>
                                       </select>
                                      </td>
                                 </tr>
                                 <tr>
                                      <td>
                                      <input type="number" name="billing[phone]" id="phone" value="<?php if($cartBillingAddress->phone){echo $cartBillingAddress->phone;}if($cartBillingAddress->telephone){echo $cartBillingAddress->telephone;} ?>"
                                              placeholder="Country" class="form-control" required>
                                      </td>
                                 </tr>
                                  <tr>    
                                      <td>
                                          Save to Address book : <input type="checkbox" name="billingSaveAddressBook">
                                      </td>
                                  </tr>                              
    </table>
<button type="submit" style="width:100px;height:25px">Submit</button> 
</form>