<?php
    $cartBillingAddress = $this->getBillingAddress();
    $countries = $this->getCountryName();
       
?>

<form action="<?php echo $this->getUrl('*/adminhtml_order/saveBillingAddress/'); ?>" Method="POST" id="cartForm">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div id="order-billing_address" class="box-right">
        <div class="entry-edit" style="position: relative;">

            <div class="entry-edit-head" style="width:309px">
                <h4 class="icon-head fieldset-legend head-billing-address">Billing Address</h4>
            </div>

            <fieldset class="np">
                <div class="order-address" id="order-billing_address_fields">
                    <div class="content" style="height: 260px;">
                        <div class="hor-scroll">
                            <table cellspacing="0" class="form-list">
                                <tbody>

                                    <tr>
                                        <td class="label"><label for="order-billing_address_street0">Street Address <span class="required">*</span></label></td>
                                        <td class="value">
                                        <input type="text" name="billing[address]" id="billingaddress" value="<?php if($cartBillingAddress->street){echo $cartBillingAddress->street;}if($cartBillingAddress->address){echo $cartBillingAddress->address;}?>"
                                                placeholder="Address" class="form-control" required>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label for="order-billing_address_city">City <span class="required">*</span></label></td>
                                        <td class="value">
                                        <input type=" text" name="billing[city]" id="billingcity" value="<?php echo $cartBillingAddress->city?>"
                                                placeholder="City" class="form-control" required>                                    </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label for="order-billing_address_country_id">Country <span class="required">*</span></label></td>
                                        <td class="value">
                                            <select id="billingcountry" name="billing[country]" class=" required-entry required-entry select" required>
                                                    <option value="">Select Country</option>
                                                    <?php foreach($countries as $key => $country):?>
                                                        <option name="country_name" value="<?php echo $country['country_id'];?>"
                                                        <?php if ($cartBillingAddress['country_id'] == $country['country_id']){ echo "Selected";}?><?php if ($cartBillingAddress['country'] == $country['country_id']){ echo "Selected";}?>>
                                                        <?php echo $country['name']?>
                                                        </option>
                                                    <?php endforeach;?>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label for="order-billing_address_region">State/Province <span class="required" style="display: none;">*</span></label>
                                        </td>
                                        <td class="value">
                                            <input type="text" name="billing[state]" id="billingstate" value="<?php if($cartBillingAddress->region){echo $cartBillingAddress->region;}if($cartBillingAddress->state){echo $cartBillingAddress->state;}?>"
                                                placeholder="State" class="form-control" required>                                    </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label for="order-billing_address_postcode">Zip/Postal Code <span class="required">*</span></label></td>
                                        <td class="value">
                                            <input type="text" name="billing[zipcode]" id="billingzipcode" value="<?php if($cartBillingAddress->zipcode){echo $cartBillingAddress->zipcode;}if($cartBillingAddress->postcode){echo $cartBillingAddress->postcode;}?>"
                                                    placeholder="Zipcode" class="form-control" required>                                    </td>
                                    </tr>
                                    <tr>
                                        <td class="label"><label for="order-billing_address_telephone">Telephone <span class="required">*</span></label></td>
                                        <td class="value">
                                            <input type="number" name="billing[phone]" id="billingphone" value="<?php if($cartBillingAddress->phone){echo $cartBillingAddress->phone;}if($cartBillingAddress->telephone){echo $cartBillingAddress->telephone;} ?>"
                                                placeholder="Country" class="form-control" required>                                    </td>
                                    </tr>
                                    <tr>
                                        <td class="value" colspan="2">
                                            <button type="submit" id="submitBtn" style="width:100px;height:25px">Submit</button>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="order-save-in-address-book">
                        <input type="checkbox" id="billingSaveAddressBook" name="billingSaveAddressBook">
                        <label for="order-billing_address_save_in_address_book">Save in address book</label>
                    </div>
                </div>
                <div style="display: none; position: absolute; background-color: rgb(153, 153, 153); opacity: 0.8; width: 300px; height: 654px; top: 0px; left: 0px;" id="address-billing-overlay" class="overlay"><span>billing address selection is not applicable</span></div>

            </fieldset>
        </div>
    </div>
</form>
