<?php
    $address = $this->getAddress();
    echo "<pre>";
    print_r($address);
    die;
?>
<table class="table">
                                  <tr>
                                      <td>
                                          <input type="text" name="billing[address]" id="address" value="<?php echo $cartBillingAddress->address?>"
                                              placeholder="Address" class="form-control">
                                      </td>
                                    </tr>  
                                    <tr>  
                                        <td>
                                          <input type=" text" name="billing[city]" id="lastname" value="<?php echo $cartBillingAddress->city?>"
                                              placeholder="City" class="form-control">
                                        </td> 
                                  </tr>
                                  <tr>
                                      <td>
                                          <input type="text" name="billing[state]" id="state" value="<?php echo $cartBillingAddress->state?>"
                                              placeholder="State" class="form-control">
                                      </td>
                                  </tr>
                                  <tr>  
                                      <td>
                                          <input type="text" name="billing[zipcode]" id="zipcode" value="<?php echo $cartBillingAddress->zipcode?>"
                                              placeholder="Zipcode" class="form-control">
                                      </td>
                                  </tr>
                                  <tr>
                                      <td>
                                      <input type="text" name="billing[country]" id="country" value="<?php echo $cartBillingAddress->country?>"
                                              placeholder="Country" class="form-control">
                                      </td>
                                 </tr>
                                  <tr>    
                                      <td>
                                          Save to Address book : <input type="checkbox" name="billingSaveAddressBook">
                                      </td>
                                  </tr>

</table>