<?php $customers = $this->getCustomers();
      $sessionCustomer = $this->getActiveCustomer();
       /* echo "<pre>";
       print_r($customers = $this->getCustomers()); 
       die;  */
 ?>
<div class="entry-edit-head"><h4>Customer</h4></div>
    <form action="<?php echo $this->getUrl('*/adminhtml_order/selectCustomer');?>" Method="POST" id="cartForm">
    <?php echo $this->getBlockHtml('formkey');?>
            <fieldset class="a-center bold">
            <span class="nowrap" style="font-size:18px;">
            <label for="cars">Choose a customer:</label>
                <select name="customer_id" id="customer_name" style="width:150px;height:30px">
                    <?php if(!$sessionCustomer):?>
                        <option>--Select--</option> 
                    <?php endif;?>
                    <?php foreach ($customers as $key => $value):?>
                    <option value="<?= $value['entity_id']?>" <?php if($value['entity_id'] == $sessionCustomer){ echo "Selected";}?>><?= $value['firstName']?> <?= $value['lastName']?></option>  
                     <?php endforeach; ?>  
                </select>  
                <br><br>   
            </span>
            
                <button type="submit" class="button" title="Save Customer" style="width:100px;height:25px">Save</button>
            
                <button type="submit" name="reset" class="button" title="reset Customer" style="width:100px;height:25px">Reset</button>
        </fieldset>
    </form>    
<script type="text/javascript">
    function selectCustomer() {
        alert(111);   
    }
</script>

    