<div class="entry-edit-head"><h4>Cart</h4></div>
<fieldset class="a-center bold">
    <span class="nowrap" >
    <center>        
            <table border=1 class="data-table" id="my-product-table" width="50%">
                <thead>
                    <tr>
                        <th><?php echo $this->__('SKU') ?></th>
                        <th><?php echo $this->__('Name') ?></th>
                        <th><?php echo $this->__('Price') ?></th>
                        <th><?php echo $this->__('Quantity') ?></th>
                        <th><?php echo $this->__('Subtotal') ?></th>
                        <th><?php echo $this->__('Discount') ?></th>
                        <th><?php echo $this->__('Row Total') ?></th>
                        <th><?php echo $this->__('Action') ?></th>
                    </tr>
                </thead>
                <tbody>
                    
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        <center>     
    </span><br>
<input type="submit" title="update cart" style="width:100px;height:25px">           
 
</fieldset>