<?php
    $products = $this->getProducts();
    $customerId = Mage::getSingleton('order/session')->getCustomerId();
    /* echo "<pre>";
    print_r($this->getProducts()); 
    die; */
?>
<div class="entry-edit-head"><h4>Product</h4></div>
    <form action="<?php echo $this->getUrl('*/adminhtml_order/addItemToCart');?>" Method="POST" id="cartForm">
        <?php echo $this->getBlockHtml('formkey');?>
        <fieldset class="a-center bold">
            <span class="nowrap">
                <center>        
                    <table class="data-table" id="my-product-table" width="50%">
                    <?php if($customerId):?>
                        <thead>
                            <tr>
                                <th><h3><?php echo $this->__('SKU') ?></h3></th>
                                <th><h3><?php echo $this->__('Name') ?></h3></th>
                                <th><h3><?php echo $this->__('Price') ?></h3></th>
                                <th><h3><?php echo $this->__('Select') ?></h3></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php foreach ($products as $product): ?>
                            <tr>
                                <td><?php echo $product['sku']; ?>&nbsp;</td>
                                <td><?php echo $product['name']; ?>&nbsp;</td>
                                <td><?php echo $product['price']; ?></td>
                                <td><input type="checkbox" id="myCheckbox" name="id[<?php echo $product['entity_id']; ?>]" ></td>
                            </tr>
                            <?php endforeach;?>
                            <?php else:?>
                            <tr>
                                <td>Please Select Customer...</td>
        
                            </tr>
                            <?php endif;?>
                        </tbody>
                    </table>
                <center>   
            </span><br>
            <?php if($customerId):?>
                <button type="submit" title="Save Product" style="width:100px;height:25px">Save</button>    
            <?php endif;?>     
        </fieldset>
    </form>    


<script language="javascript">
    function enableDisable(bEnable, textBoxID)
    {
         document.getElementById(textBoxID).disabled = !bEnable
         //alert(111);
    }
</script>