<div class="entry-edit-head"><h4>Total Price</h4></div>
<fieldset class="a-center bold">
    <span class="nowrap" style="">
        <table width="30%">
            <tr>
                <td>Subtotal</td>
                <td></td>
            </tr>
            <tr>
                <td><h3>Grand total</h3></td>
                <td></td>
            </tr>
        </table>
        <input type="submit" title="Save Order" style="width:100px;height:25px">             
    </span>
</fieldset>