<?php
    echo "<pre>";
    //print_r($this->getShippingMethod());
    foreach($this->getShippingMethod() as $_code => $_method){
        // Get the first allowed method of this shipping carrier
        /* $m = key($_method->getAllowedMethods()); 
       echo  $shipping_method = $_code . '_' . $m."<br>"; */
       print_r($_method->getAllowedMethods());
       echo "<br>";
      
    }
    die; 
?>