<?php
$paymentMethod = $this->getPayemntMethodTitle();
$methods = [];
foreach ($paymentMethod as $key => $value) {
    $methods[$value->getCode()] = $value->getTitle();
}

?>

<form action="<?php echo $this->getUrl('*/adminhtml_order/savePaymentMethod/'); ?>" Method="POST" id="cartForm">
    <?php echo $this->getBlockHtml('formkey'); ?>
    <div class="entry-edit" style="position: relative;">
        <div class="entry-edit-head">
            <div style="float: right;"></div>
            <h4 class="fieldset-legend head-shipping-method icon-head">Shipping Method</h4>
        </div>
        <div class="fieldset">
            <div id="order-shipping-method-choose" style="">
                <table width="20%" heigth=20%>

                    <?php foreach ($methods as $code => $title) : ?>

                        <tr>
                            <td><b><?= $title ?></b></td>
                            <td><input type="radio" value="<?= $code ?>=><?= $title ?>" name="paymentMethod" <?php //if($code == $this->getCart()->payment_method_code()){echo "Checked";}
                                                                                                                ?> required>
                            </td>
                        </tr>

                    <?php endforeach; ?>
                    <tr>
                        <td colspan=3><button type="submit" style="width:100px;height:25px">Submit</button> </td>
                    </tr>
                </table>
            </div>
        </div>
</form>