<?php
    $cartShippingAddress = $this->getShippingAddress();
    $countries = $this->getCountryName();
    $sameAsBilling = $this->getSameAsBilling();
  /*  echo "<pre>";
    print_r( $this->getCart()->getBillingAddress()->getId());
    die; */

?>
<form action="<?php echo $this->getUrl('*/adminhtml_order/saveShippingAddress/');?>" Method="POST" id="cartForm">
    <?php echo $this->getBlockHtml('formkey');?>
    <table class="table">
                                <?php if($this->getCart()->getBillingAddress()->getId()):?>

                                  <tr>
                                      <td colspan="2">
                                          Same as Billing Address : &nbsp<input type="checkbox" name="sameasbilling"class="form-check-input" id="sameasbilling" onclick="myCheckbox();"
                                          <?php if ($sameAsBilling){echo "Checked";}?> >
                                      </td>
                                  </tr>
                                <?php endif;?>  
                                  <tr>
                                      <td>
                                          <input type="text" name="shipping[address]" id="shippingAddress" value="<?php if($cartShippingAddress->street){echo $cartShippingAddress->street;}if($cartShippingAddress->address){echo $cartShippingAddress->address;}?>"
                                              placeholder="Address" class="form-control" <?php if ($sameAsBilling){echo "Disabled";}?>>
                                      </td>
                                  </tr>
                                  <tr>    
                                      <td>
                                          <input type=" text" name="shipping[city]" id="shippingCity" value="<?php echo $cartShippingAddress->city;?>"
                                              placeholder="City" class="form-control" <?php if ($sameAsBilling){echo "Disabled";}?>>
                                      </td>
                                  </tr>
                                  <tr>
                                      <td>
                                          <input type="text" name="shipping[state]" id="shippingState" value="<?php if($cartShippingAddress->region){echo $cartShippingAddress->region;}if($cartShippingAddress->state){echo $cartShippingAddress->state;}?>"
                                              placeholder="State" class="form-control" <?php if ($sameAsBilling){echo "Disabled";}?>>
                                      </td>
                                  </tr>
                                  <tr>    
                                      <td>
                                          <input type="text" name="shipping[zipcode]" id="shippingZipcode" value="<?php if($cartShippingAddress->zipcode){echo $cartShippingAddress->zipcode;}if($cartShippingAddress->postcode){echo $cartShippingAddress->postcode;}?>"
                                              placeholder="Zipcode" class="form-control" <?php if ($sameAsBilling){echo "Disabled";}?>>
                                      </td>
                                  </tr>
                                  <tr>
                                      <td>
                                      <select id="shippingCountry" name="shipping[country]" <?php if ($sameAsBilling){echo "Disabled";}?>>
                                            <option value="">Select Country</option>
                                            <?php foreach($countries as $key => $country):?>
                                                <option name="country_name" value="<?php echo $country['country_id'];?>"
                                                 <?php if ($cartShippingAddress['country_id'] == $country['country_id']){ echo "Selected";}?><?php if ($cartShippingAddress['country'] == $country['country_id']){ echo "Selected";}?>>
                                                 <?php echo $country['name']?>
                                                 </option>
                                            <?php endforeach;?>
                                       </select>
                                      </td>
                                  </tr>
                                  <tr>
                                      <td>
                                      <input type="phone" name="shipping[phone]" id="shippingPhone" value="<?php if($cartShippingAddress->phone){echo $cartShippingAddress->phone;}if($cartShippingAddress->telephone){echo $cartShippingAddress->telephone;} ?>"
                                              placeholder="phone" class="form-control" <?php if ($sameAsBilling){echo "Disabled";}?>>
                                      </td>
                                 </tr>
                                  <tr>    
                                      <td>
                                          Save to Address book : <input type="checkbox" id="shippingSaveAddressBook" name="shippingSaveAddressBook">
                                      </td>
                                  </tr>
                                  
    </table>
    <button type="submit" style="width:100px;height:25px" id="shippingButton" name="shippingButton">Submit</button> 
</form>    
                      